import { ExternalLink, GitFork, Star } from "lucide-react";
import Image from "next/image";
import { profile } from "@/data/profile";
import { getGithubProfile, getGithubRepos } from "@/lib/github";

export async function GitHubSection() {
  const githubProfile = await getGithubProfile();
  const repos = (await getGithubRepos()).filter((repo) => !/summar|summera/i.test(repo.name)).slice(0, 3);

  return <section id="github" className="section-wrap"><div className="section-head"><span className="section-index">09</span><div><h2>Public work, in motion.</h2><p>GitHub / live repository data</p><div className="hairline mt-6" /></div></div>{githubProfile ? <div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div className="border border-border bg-card p-6"><div className="flex items-center gap-4"><Image src={githubProfile.avatar_url} alt="GitHub profile avatar" width={64} height={64} className="h-16 w-16 object-cover" /><div><h3 className="text-xl font-semibold">{githubProfile.name ?? githubProfile.login}</h3><p className="text-sm text-muted">@{githubProfile.login}</p></div></div><p className="mt-5 leading-7 text-muted">{githubProfile.bio ?? "Public repositories and ongoing experiments from Jeevan's GitHub."}</p><div className="mt-7 grid grid-cols-3 border-y border-border py-4 text-center"><div><strong className="block text-xl font-semibold text-foreground">{githubProfile.public_repos}</strong><span className="technical-label">Repos</span></div><div className="border-x border-border"><strong className="block text-xl font-semibold text-foreground">{githubProfile.followers}</strong><span className="technical-label">Followers</span></div><div><strong className="block text-xl font-semibold text-foreground">{githubProfile.following}</strong><span className="technical-label">Following</span></div></div><a href={profile.githubUrl} target="_blank" rel="noreferrer" className="mt-7 inline-flex items-center gap-2 text-sm text-foreground hover:text-accent">Explore all public work <ExternalLink size={14} /></a></div><div className="grid gap-3">{repos.length ? repos.map((repo) => <a className="mini-card block transition hover:-translate-y-1 hover:border-accent" href={repo.html_url} target="_blank" rel="noreferrer" key={repo.name}><div className="flex items-start justify-between gap-4"><div><span className="technical-label">Repository</span><h3>{repo.name}</h3></div><ExternalLink size={15} className="text-muted" /></div><p className="text-sm leading-6 text-muted">{repo.description ?? "Public repository with ongoing development."}</p><div className="mt-5 flex gap-4 text-xs text-muted"><span><Star size={12} className="mr-1 inline" />{repo.stargazers_count}</span><span><GitFork size={12} className="mr-1 inline" />{repo.forks_count}</span><span>{repo.language ?? "Code"}</span></div></a>) : <p className="text-sm text-muted">Recent repository data is temporarily unavailable.</p>}</div></div> : <div className="border border-border p-6 text-muted">GitHub profile data is temporarily unavailable. Visit <a className="text-foreground underline" href={profile.githubUrl}>the verified profile</a> to explore Jeevan&apos;s public work.</div>}</section>;
}
